### ISSUE TITLE
is file_htm an xml or htm file?

### ISSUE THREAD

**Issue by snayeri** [areed1192/sigma_coding_youtube#11]
I think the code mistakenly tried to parse an HTML file. here are a few lines from the raw code:

```
# Define the file path.
file_htm = sec_directory.joinpath('fb-09302019x10q.htm').resolve()
file_cal = sec_directory.joinpath('fb-20190930_cal.xml').resolve()
file_lab = sec_directory.joinpath('fb-20190930_lab.xml').resolve()
file_def = sec_directory.joinpath('fb-20190930_def.xml').resolve()

```
The first file is the path for an HTML file, but I think the parser is configured for XML file. Perhaps that is why the code gives me the full structure in the CSV file, but no values!

**Comment by areed1192** [comment]
The file extension is correct, the SEC has `htm` files in some of the filing directories.
