### ISSUE TITLE
Task exception was never retreived for Data Streaming.

### ISSUE THREAD

**Issue by AlphaAmongBetas** [areed1192/sigma_coding_youtube#12]
HI Alex,

I run your code as you have written it. 
When I run the code at the top I always see a print message " Connection established. Client correctly connected"
When I run the code I might see either Response for **LevelOne_futures_options**, **Active_Nasdaq**, **Quote**, or all of them combined. Then followed by a statement: 
"Connection with server closed" 
"Task exception was never retrieved"
Then followed by an error message, RuntimeError: cannot call recv while another coroutine is already waiting for the next message.
I have attached the screenshots of the error messages.

Other times the code works continuously as intended without interrupting.
 

Would you know what this issue can be attributed to, whether it has something to do with my internet connection, bug in the server or a bug in the websockets and possibly if you know how to get around it. 

**Screenshots**
<img width="1426" alt="Screen Shot 2020-12-08 at 6 50 22 PM" src="https://user-images.githubusercontent.com/74377857/101560840-c8f90d80-3989-11eb-9fc6-61e1afc36c74.png">
<img width="1419" alt="Screen Shot 2020-12-08 at 6 49 17 PM" src="https://user-images.githubusercontent.com/74377857/101560843-cb5b6780-3989-11eb-852d-92d2a982dfdf.png">
<img width="1430" alt="Screen Shot 2020-12-08 at 6 49 50 PM" src="https://user-images.githubusercontent.com/74377857/101560846-cbf3fe00-3989-11eb-801f-b336f2f2e221.png">

 - OS: [ MacOs]
 - Browser [chrome]

**Comment by dss010101** [comment]
I am getting this same error.  im wondering if it is related to a version update of asyncio.  what version was this code originally written against?
