### ISSUE TITLE
Web Scraping SEC - EDGAR Queries.ipynb 

### ISSUE THREAD

**Issue by PSause** [areed1192/sigma_coding_youtube#3]
Hi

this part of the code triggers error ==> IndexError: list index out of range

- Web Scraping SEC - EDGAR Queries.ipynb
- Section Two: Parse the Response for the Document Details
-In [63]:

filing_date = cols[3].text.strip()
filing_numb = cols[4].text.strip()

does this happen for anyone else as well?

thx and amazing job!!!

**Comment by areed1192** [comment]
If there are less than five columns, then yes it will raise an error. You would need to adjust the script so that it would only parse the number of columns found in the table.
