### ISSUE TITLE
TD Standard API.Py : issue with refresh token

### ISSUE THREAD

**Issue by lmsanch** [areed1192/sigma_coding_youtube#5]
Alex:

thank you for the great tutorial about how to access TDAmeritrade accounts in youtube via API. I have a question, from a code I have been playing with.

The authentication returns 2 tokens, one that expires in 30 minutes and the other one that expires in 3 months (the refresh_token).

Your code shows how to access the functionality by using the access token. I saved my access token and refresh token in an environment file.

After 30 minutes, the access token expires..how do I acess the functionality with the refresh_token?

Do I have to modify this?
`headers = {'Authorization': "Bearer {}".format(access_token)}`

> The documentation states this about refresh_tokens:
> To request a new access token, make a Post Access Token request with your refresh token using the following parameter values:
> 
>     grant_type: refresh_token
>     refresh_token: {REFRESH TOKEN}
>     client_id: {Consumer Key}

Not sure how to implement this,
Thank you

**Comment by areed1192** [comment]
Hey Luis, in the standard API I didn't add to code to do this. However, if you go to my repository that is dedicated to the TD API client library you'll see the section that handles grabbing a refresh token. If you go to the client.py file you'll find a method called `token_refresh` that will demonstrate the request to get a refresh token. Here is the link to the file: [Client.py](https://github.com/areed1192/td-ameritrade-python-api/blob/master/td/client.py)

**Comment by lmsanch** [comment]
Thank you! Cheers
